### ISSUE TITLE
Wrong endpoint

### ISSUE THREAD

**Issue by PaLaMuNDeR** [eci-lasso/single-project-form#3]
According to this documentation the endpoint should be
[https://constructionsupport.ecisolutions.com/s/article/Lasso-Integrations-Integrate-Online-Form-Registration-Page-with-Lasso#aboutform](https://app.lassocrm.com/registrant_signup/)

**Comment by eci-lasso** [comment]
Instructions for PHP and JSON submissions are in the readme: https://github.com/eci-lasso/single-project-form#readme
